name: My dummy workflow
on: push

jobs:
  run-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: docker://java:8
      - run: ./gradlew clean test
  build-docker-image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: echo "hello world!"
      - run: ls
