name: My dummy workflow
on: push

jobs:
  build:
    runs-on: openjdk:8
    #runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: echo "hello world!"
      - run: ls
      #- run: ./gradlew clean test
