name: My dummy workflow
on: push

jobs:
  run-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - run: ./gradlew clean test
  run-tests-in-docker:
    runs-on: ubuntu-18.04
    container:
      image: java:8-jdk
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew clean test
      - name: Use secret
        env:
          THE_SECRET: ${{secrets.MY_SECRET}}
        run: |
          echo "The secret is: ${THE_SECRET}"
  build-docker-image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: docker build .
