name: My dummy workflow
on: push

jobs:
  run-tests:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - run: ./gradlew clean test
  run-tests-in-docker:
    runs-on: ubuntu-18.04
    container:
      image: ubuntu:18.04
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew clean test
  build-docker-image:
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: docker build .
