name: Build on push
on: push

jobs:
  run-tests:
    name: Run tests without Docker
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - uses: actions/setup-java@v1
        with:
          java-version: '8'
      - run: ./gradlew clean test
  run-tests-in-docker:
    name: Run tests in Docker
    runs-on: ubuntu-18.04
    container:
      image: java:8-jdk
    steps:
      - uses: actions/checkout@v1
      - run: ./gradlew clean test
  build-docker-image:
    name: Build Docker image
    runs-on: ubuntu-18.04
    steps:
      - uses: actions/checkout@v1
      - run: docker build .
  use-context:
    name: Use the build context
    runs-on: ubuntu-18.04
    steps:
      - name: Use context
        env:
          THE_SECRET: ${{secrets.MY_SECRET}} # create manually using Github UI
          THE_NOT_SECRET: qwerty
          GITHUB_REF: ${{github.ref}}
          GITHUB_SHA: ${{github.sha}}
        run: |
          echo "The secret: ${THE_SECRET}"
          echo "The not secret: ${THE_NOT_SECRET}"
          echo "Github ref: ${GITHUB_REF}"
          echo "Github SHA: ${GITHUB_SHA}"
